import { imageGallery } from '../../data/imageGallery';
import { set, nine, choice, numeric, selection, card, stableChoiceOrder, labelDisplayedChoices } from './helpers';
import { picture, text, rect, circle, line, grid, dots, panels, mosaic, clock, palette, image } from './draw';
import type { Primitive } from './draw';
import { partitionDiagram } from './task-diagrams';
const equation = (s: string) => picture([text(300, 135, s, 42)]);
export function fractionPaper(count: number, filled: number, columns: number) {
    const rows = count / columns, w = 360 / columns, h = 240 / rows;
    return picture(Array.from({ length: count }, (_, i) => rect(20 + i % columns * w, 20 + Math.floor(i / columns) * h, w, h, i < filled ? '#c4dacb' : '#fffdf7')), 400, 280);
}

const bars = (tens: number, ones: number) => picture([
    ...Array.from({ length: tens }, (_, i) => rect(30 + i * 48, 30, 32, 180, palette[1])),
    ...Array.from({ length: ones }, (_, i) => rect(210 + i % 5 * 42, 45 + Math.floor(i / 5) * 52, 27, 27, palette[2])),
    text(100, 250, '一长条代表10', 22), text(340, 250, '一小块代表1', 22),
]);
export const mathSets = [
    set('N01', '数量结构屋', nine((i, s, v) => { const n = [7, 12, 17][s] + v; return numeric('N01', i, '图里一共有多少个圆点？', n, [n - 1, n + 1, n + 5], `一共有${n}个。可以先把完整的一组数出来，再加上剩下的。`, dots(n, s === 0 ? 4 : 5, palette[s], s === 2 ? 1.1 : 1), { operation: 'identity', values: [n] }); })),
    set('N02', '移一移比多少', nine((i, s, v) => { const left = 5 + v, right = left + (s === 2 ? 2 * (v + 1) : 2 + s + v), answer = s === 2 ? (right - left) / 2 : right - left; const a = numeric('N02', i, s === 2 ? '从右边移几个到左边，两边就一样多？' : '左边还要添几个，才和右边一样多？', answer, [right - left + 1, left, s === 2 ? right - left : answer + 2], s === 2 ? `每移一个，左边多一个，右边少一个。移${answer}个以后，两边一样多。` : `把两边一一配对，右边多出${answer}个，左边就补${answer}个。`, panels([{ title: '左边', drawing: dots(left) }, { title: '右边', drawing: dots(right) }]), { operation: s === 2 ? 'halfDifference' : 'difference', values: [right, left] }); a.presentation = { evidence: { kind:'visualComparison', panels:[{kind:'dots',label:'左边',count:left,columns:5},{kind:'dots',label:'右边',count:right,columns:5}] } }; return a; })),
    set('N03', '变了样没变多', nine((i, s, v) => { const n = 6 + v + s * 3; const art = s < 2 ? panels([{ title: '原来的排法', drawing: dots(n, 3) }, { title: '重新摆开，没有增减', drawing: dots(n, n, palette[1], 1.05) }]) : picture([rect(70, 90, 90, 145), rect(75, 155, 80, 75, '#9dc9e8'), text(115, 265, `原来${n}杯`, 25), text(300, 160, '全部倒入 →', 28), rect(420, 100, 140, 135), rect(425, 185, 130, 45, '#9dc9e8'), text(490, 270, '没有洒出', 23)]); const a = numeric('N03', i, s < 2 ? '重新摆开以后，有多少个圆点？' : '把水全部倒进宽杯，水量相当于原来的几小杯？', n, [n - 1, n + 1, n + 2], s < 2 ? `还是${n}个。间距和排法变了，没有添进或拿走圆点。` : `还是${n}小杯的水。题目说明全部倒入且没有洒出，水面高低不能直接表示水量多少。`, art, { operation: 'identity', values: [n] }, s === 2 ? ['这里比较水量，不比较水面有多高。'] : []); if (s < 2) a.presentation = { evidence: { kind:'visualComparison', panels:[{kind:'dots',label:'原来的排法',count:n,columns:3},{kind:'dots',label:'重新摆开，没有增减',count:n,columns:Math.min(n,6)}] } }; return a; })),
    set('N04', '分法找齐了吗', nine((i, s, v) => { const n = 5 + v; const pairs = Array.from({ length: n + 1 }, (_, a) => [a, n - a]); pairs.push([n, 1]); const valid = pairs.flatMap(([a, b], k) => (a + b === n && (s < 1 || a > 0 && b > 0) && (s < 2 || a < b)) ? [`p${k}`] : []); return selection('N04', i, `把${n}个圆片分进两个盒子，哪些分法符合要求？`, pairs.map(([a, b], k) => card(`p${k}`, `左${a}右${b}`, partitionDiagram(a, b))), valid, `总数必须是${n}。${s > 0 ? '每盒都要有。' : ''}${s > 1 ? '左盒还要比右盒少。' : ''}按左盒从少到多列出，就不容易漏。`, undefined, [`两盒合起来是${n}。`, ...(s > 0 ? ['每个盒子至少有一个。'] : []), ...(s > 1 ? ['左盒比右盒少。'] : [])]); })),
    set('N05', '十的好朋友', nine((i, s, v) => { const a = s === 0 ? 6 + v : s === 1 ? 8 + v : 13 + v, b = s === 0 ? 10 : s === 1 ? 5 + v : 7 + v; const answer = s === 0 ? 10 - a : s === 1 ? a + b : a - b; const art = s === 0 ? grid(Array.from({ length: 10 }, (_, k) => k < a ? '●' : ''), 5) : panels([{ title: `${a}`, drawing: bars(Math.floor(a / 10), a % 10) }, { title: s === 1 ? `再加${b}` : `拿走${b}`, drawing: dots(b) }]); const activity = numeric('N05', i, s === 0 ? '十格框里还差几个就满十个？' : s === 1 ? `${a}加${b}等于多少？先试试凑成十。` : `${a}减${b}等于多少？试试先从十里面拿。`, answer, [answer - 1, answer + 1, s === 2 ? a + b : a + b + 1], s === 0 ? `${a}再添${answer}正好是十。` : s === 1 ? `把${b}拆成${10 - a}和${b - (10 - a)}，先凑十，再加剩下的，得到${answer}。` : `十减${b}剩${10 - b}，再和个位的${a - 10}合起来，是${answer}。`, art, { operation: s === 1 ? 'add' : 'subtract', values: s === 0 ? [10, a] : [a, b] }); if(s > 0) activity.presentation = { evidence:{kind:'visualComparison',panels:[{kind:'placeValue',label:String(a),tens:Math.floor(a/10),ones:a%10},{kind:'dots',label:s===1?`再加${b}`:`拿走${b}`,count:b,columns:5}] } }; return activity; })),
    set('N06', '故事里的未知数', nine((i, s, v) => { const start = 7 + v, change = 3 + v, end = start + change; const answer = s === 0 ? end : s === 1 ? start : change; const prompt = s === 0 ? `树上有${start}只鸟，又飞来${change}只，现在有几只？` : s === 1 ? `又飞来${change}只鸟以后，树上有${end}只。原来有几只？` : `树上原来有${start}只鸟，后来变成${end}只。飞来了几只？`; const activity = numeric('N06', i, prompt, answer, [answer - 1, answer + 1, start + end], s === 0 ? `${start}和${change}合起来是${end}。` : s === 1 ? `从现在的${end}只里去掉后来飞来的${change}只，原来有${start}只。` : `现在比原来多${change}只，所以飞来了${change}只。`, equation(s === 0 ? `${start} + ${change} = ?` : s === 1 ? `? + ${change} = ${end}` : `${start} + ? = ${end}`), { operation: s === 0 ? 'add' : 'subtract', values: s === 0 ? [start, change] : s === 1 ? [end, change] : [end, start] }); activity.presentation = { evidence: { kind: 'quantityStory', parts: [{ label: '原来', count: s === 1 ? null : start }, { label: '飞来了', count: s === 2 ? null : change }, { label: '现在', count: s === 0 ? null : end }] } }; return activity; })),
    set('N07', '分组小管家', nine((i, s, v) => { const groups = 3 + v, each = s === 0 ? 3 : 4, remainder = s === 2 ? 1 + v : 0, total = groups * each + remainder; const answer = s === 0 ? each : s === 1 ? total : remainder; const activity = numeric('N07', i, s === 0 ? `${total}块饼干平均分给${groups}个人，每人几块？` : s === 1 ? `每盒有${each}个圆片，${groups}盒一共几个？` : `${total}个圆片每${each}个装一盒，装完尽量多的整盒后，还剩几个？`, answer, [answer + 1, answer - 1, groups], s === 2 ? `${total}里有${groups}组${each}，还有${remainder}个不够装一盒。` : `${groups}组，每组${each}个，合起来是${groups * each}。`, dots(total, each), { operation: s === 0 ? 'divide' : s === 1 ? 'multiply' : 'remainder', values: s === 0 ? [total, groups] : s === 1 ? [groups, each] : [total, each] }); if (s === 0) activity.presentation = { evidence: { kind: 'collection', count: total, image: imageGallery.items.cookie, caption: `${total}块饼干，平均分给${groups}个人` } }; return activity; })),
    set('N08', '一样大的那一份', nine((i, s, v) => { const parts = [2, 3, 4][v], filled = s === 0 ? 1 : s === 1 ? parts - 1 : 1, baseCount = parts * (s + 1), baseFill = filled * (s + 1); const optCount = parts * (s + 2), optFill = filled * (s + 2); const art = fractionPaper(baseCount, baseFill, parts); const option = (count: number, fill: number) => fractionPaper(count, fill, parts); return choice('N08', i, '哪张图的绿色部分占整张纸的比例，和上面一样？', [{ label: '图A', drawing: option(optCount, optFill) }, { label: '图B', drawing: option(optCount, optFill - 1) }, { label: '图C', drawing: option(optCount, Math.min(optCount, optFill + 1)) }], 0, `上图的${baseCount}个等大格里有${baseFill}个绿色格。正确图虽然分得更细，绿色部分仍占同样的比例。`, art, ['每张纸里的小格一样大。', '比较绿色占整张纸的比例。']); })),
    set('N09', '队伍有多长', nine((i, s, v) => { const left = 3 + v, right = 4 + v, n = left + right - 1; const activity = numeric('N09', i, s === 0 ? `小兔从左数第${left}，后面还有${right - 1}位朋友。队伍一共有几位？` : s === 1 ? `小兔从左数第${left}，从右数第${right}。队伍一共有几位？` : `两个数队伍的小朋友都数到了小兔。左边这组含小兔有${left}位，右边这组含小兔有${right}位。合起来有几位？`, n, [n + 1, n - 1, left + right + 1], `两边都数到小兔，小兔重复了一次。${left}加${right}再减一，是${n}。`, picture([rect(30, 70, 300, 120, '#d9e8f4'), rect(270, 70, 300, 120, '#e3ecd4'), text(155, 115, `从左含小兔${left}位`, 22), text(440, 155, `从右含小兔${right}位`, 22), circle(300, 130, 20, palette[0])]), { operation: 'overlap', values: [left, right, 1] }); activity.presentation = { evidence: { kind: 'overlapQueue', left, right } }; return activity; })),
    set('N10', '单双和数位', nine((i, s, v) => { if (s === 0) {
        const nums = Array.from({ length: 6 }, (_, k) => k + 5 + v);
        return selection('N10', i, '哪些数量能两两牵手，刚好没有剩下？', nums.map(n => card(`n${n}`, n, dots(n, 2))), nums.filter(n => n % 2 === 0).map(n => `n${n}`), '能两两配完，没有落单，就是双数。最后多出一个就是单数。');
    } const tens = 2 + v, ones = 3 + v, n = tens * 10 + ones; const activity = numeric('N10', i, s === 1 ? '这些长条和小方块一共表示多少？' : `原来有${n}个，拿走一个以后是多少？`, s === 1 ? n : n - 1, [s === 1 ? tens + ones : n + 1, n + 10, n - 10], s === 1 ? `${tens}个十和${ones}个一，组成${n}。` : `${n}拿走一变成${n - 1}。每增加或减少一个，单双都会改变。`, bars(tens, ones), { operation: s === 1 ? 'placeValue' : 'subtract', values: s === 1 ? [tens, ones] : [n, 1] }); if (s === 2) activity.parentPrompt = `先听孩子说：${n}是单数还是双数？拿走一个以后呢？请用两两配对解释。这部分由家长口头观察，数字选项只检查剩下的数量。`; return activity; })),
    set('N11', '数列侦探', nine((i, s, v) => { const step = 2 + v, start = 1 + v; const seq = s === 0 ? [start, start + step, start + 2 * step, start + 3 * step] : s === 1 ? [start, 20 + v, start + step, 22 + v, start + 2 * step, 24 + v] : [start, start + step, start + 2 * step, start + 3, start + 3 + step, start + 3 + 2 * step]; const answer = seq[seq.length - 1]; return numeric('N11', i, s === 2 ? '按行和列的变化，补出最后一个数。' : '先找变化规律，再补出问号处的数。', answer, [answer - 1, answer + 1, answer + step], s === 0 ? `每次增加${step}，所以接下来是${answer}。` : s === 1 ? `隔一个分成两队。第一队每次加${step}，第二队每次加二，问号属于第二队。` : `每行从左到右加${step}，每列从上到下加三，两条规则都得到${answer}。`, grid([...seq.slice(0, -1), '?'], s === 2 ? 3 : seq.length), { operation: 'identity', values: [answer] }); })),
    set('N12', '图形等量换', nine((i, s, v) => { const a = 3 + v, b = 2 + v, answer = s === 0 ? a : s === 1 ? b : a + 2 * b; const o: Primitive[] = [text(300, 60, `○ + ○ = ${a * 2}`, 36)]; if (s > 0)
        o.push(text(300, 130, `○ + △ = ${a + b}`, 36)); o.push(text(300, 215, s === 0 ? '○ = ?' : s === 1 ? '△ = ?' : '○ + △ + △ = ?', 36)); return numeric('N12', i, '一样的图形表示一样的数。问号是多少？', answer, [answer - 1, answer + 1, a + b], s === 0 ? `两个圆合起来是${a * 2}，每个圆是${a}。` : s === 1 ? `圆是${a}，${a + b}去掉${a}，三角形是${b}。` : `圆是${a}，三角形是${b}，所以${a}加${b}再加${b}等于${answer}。`, picture(o), { operation: s === 0 ? 'divide' : s === 1 ? 'subtract' : 'add', values: s === 0 ? [a * 2, 2] : s === 1 ? [a + b, a] : [a, b, b] }); })),
    set('N13', '小小零钱铺', nine((i, s, v) => { if (s < 2) {
        const cost = s === 0 ? [5, 5, 10][v] : 3 + v, pay = s === 0 ? [10, 20, 50][v] : 10;
        const activity = numeric('N13', i, s === 0 ? `把一张${pay}元纸币换成${cost}元纸币，能换几张？` : `买${cost}元的东西，付10元，应找回几元？`, s === 0 ? pay / cost : pay - cost, [s === 0 ? 3 : pay + cost, cost, 1], s === 0 ? `${pay}里面有${pay / cost}个${cost}，可以换${pay / cost}张。` : `付的钱减去价格，${pay}减${cost}，找回${pay - cost}元。`, equation(s === 0 ? `${pay}元 → ${cost}元 × ?` : `10元 − ${cost}元 = ?`), { operation: s === 0 ? 'divide' : 'subtract', values: [pay, cost] }); if (s === 1) activity.presentation = { evidence: { kind: 'shopping', cost, paid: pay } }; return activity;
    }
      const scenarios = [
        { target: 5, ones: 4, plans: [[5], Array(5).fill(1), [5, 1], Array(4).fill(1)] },
        { target: 6, ones: 3, plans: [[5, 1], Array(6).fill(1), [5, 1, 1], [5]] },
        { target: 10, ones: 10, plans: [[5, ...Array(5).fill(1)], Array(10).fill(1), [5, 5], [5, ...Array(4).fill(1)]] },
      ];
      const { target, ones, plans } = scenarios[v];
      const options = labelDisplayedChoices(stableChoiceOrder(plans.map((p, k) => ({
        ...card(`p${k}`, `方案${k + 1}`, grid(p.map(n => `${n}元`), p.length)), moneyValues: p,
        speechText: [p.filter(n => n === 5).length ? `${p.filter(n => n === 5).length}张5元纸币` : '', p.filter(n => n === 1).length ? `${p.filter(n => n === 1).length}枚1元硬币` : ''].filter(Boolean).join('，'),
      })), `N13-payments-${i}`));
      const expected = plans.flatMap((p, k) => p.reduce((sum, n) => sum + n, 0) === target && p.filter(n => n === 5).length <= 1 && p.filter(n => n === 1).length <= ones ? [`p${k}`] : []);
      const a = selection('N13', i, `手里有1张5元纸币和${ones}枚1元硬币。哪些方案能刚好付${target}元？`, options, expected,
        `合计要正好是${target}元，还要检查每种钱币没有超过手里的数量。总额相同，手里的钱也不一定够用。`, undefined,
        [`刚好付${target}元。`, `最多用1张5元纸币和${ones}枚1元硬币。`]);
      a.revision = 2;
      a.presentation = { evidence: { kind: 'moneyInventory', fives: 1, ones } };
      return a;
    })),
    set('N14', '时钟往前走', nine((i, s, v) => { const hour = 3 + v, minute = s === 0 ? 30 : s === 1 ? 15 + v * 10 : 20; const delta = 25 + v * 10; const a = s < 2 ? choice('N14', i, '钟面上是几点几分？', [`${hour}点${minute}分`, `${hour + 1}点${minute}分`, `${hour}点${(minute + 5) % 60}分`], 0, `长针指${minute}分，短针已经走过${hour}，所以是${hour}点${minute}分。`, clock(hour, minute)) : numeric('N14', i, '从左边的时刻走到右边，经过了几分钟？', delta, [delta + 5, delta - 5, 60 - delta], `长针每走一个小刻度是一分钟。一共走了${delta}个小刻度，所以经过${delta}分钟。`, panels([{ title: '开始', drawing: clock(hour, minute) }, { title: '结束', drawing: clock(hour + Math.floor((minute + delta) / 60), (minute + delta) % 60) }]), { operation: 'subtract', values: [hour * 60 + minute + delta, hour * 60 + minute] }, ['这次活动不到一小时。']); if(s === 2) a.presentation = { evidence:{kind:'visualComparison',panels:[{kind:'image',label:'开始',image:image(clock(hour,minute),'开始时刻的钟面')},{kind:'image',label:'结束',image:image(clock(hour + Math.floor((minute + delta) / 60),(minute + delta) % 60),'结束时刻的钟面')}] } }; return a; })),
    set('N15', '量一量围一围', nine((i, s, v) => { const a = 4 + v, b = 2 + v, start = s === 1 ? 2 + v : 0, answer = s === 2 ? 2 * (a + b) : a; const objects: Primitive[] = s === 2 ? [rect(160, 50, a * 35, b * 35, '#dceadc'), text(300, 40, `${a}格`, 24), text(110, 115, `${b}格`, 24)] : [rect(65 + start * 38, 50, a * 38, 46, palette[2]), line(65, 140, 550, 140), ...Array.from({ length: 13 }, (_, k) => [line(65 + k * 38, 135, 65 + k * 38, 150), text(65 + k * 38, 182, k, 20)]).flat()]; return numeric('N15', i, s === 2 ? '沿长方形的四条边走一圈，一共多少格？' : '黄色纸条从一个刻度到另一个刻度，长多少格？', answer, [s === 2 ? a + b : start + a, s === 2 ? a * b : answer + 1, answer - 1], s === 2 ? `两条长边各${a}格，两条短边各${b}格，合起来${answer}格。` : `从${start}数到${start + a}，中间有${a}个单位格，长度是${a}格。`, picture(objects), { operation: s === 2 ? 'perimeter' : 'subtract', values: s === 2 ? [a, b] : [start + a, start] }); })),
    set('N16', '练习日历', nine((i, s, v) => { const day = 8 + v * 3, days = ['一', '二', '三', '四', '五', '六', '日']; const cal = grid([...days.map(n => `周${n}`), ...Array.from({ length: 28 }, (_, n) => n + 1)], 7); return s === 0 ? choice('N16', i, `这张练习日历里，${day}号是星期几？`, [0, 1, 2].map(k => `星期${days[(day - 1 + k) % 7]}`), 0, `找到${day}号所在的一列，再看列上方的星期。`, cal) : numeric('N16', i, s === 1 ? `${day}号的整整一周以后，是几号？` : `从${2 + v}号开始，每过三天浇一次水，第三次是几号？`, s === 1 ? day + 7 : 8 + v, [s === 1 ? day + 6 : 5 + v, s === 1 ? day + 8 : 11 + v, s === 1 ? day + 14 : 7 + v], s === 1 ? `一周是七天，${day}加七是${day + 7}。` : `第一次${2 + v}号，第二次${5 + v}号，第三次${8 + v}号。开始那次也算一次。`, cal, { operation: 'add', values: s === 1 ? [day, 7] : [2 + v, 3, 3] }); })),
];
